#!/bin/bash
# Προγραμματάκι που παράγει τυχαίους κωδικούς σε
# τρεματικό με Android συσκευή με βάση την /dev/urandom
# Πηγή: http://cerebrux.net/2016/05/11/dimiourgia-tuxaion-kodikon-termatiko-dev-random
# -------------cerebrux.net--------------------

for apotelesma in `seq 1 5`
    # Προβολή των 10 ψηφίων της /dev/urandom 
    # απο 1 έως 5 φορές
    do
        strings /dev/urandom | tr -d '[:space:]' | head -c 10
        echo ""
    done
